### ISSUE TITLE
head_lookAt_anim control not in direction of head_anim

### ISSUE THREAD

**Issue by broco1001** [jjburton/cgmTools#196]
![image](https://user-images.githubusercontent.com/77574628/105996528-0867ee80-60dd-11eb-9fbe-2f0e86c1424e.png)

why head_lookAt_anim control not in direction of head_anim?

**Comment by jjburton** [comment]
@broco1001 | We're not really doing the head aim thing now because it causes other issues with long neck stuff. I've been meaning to deprecate it. I'll check that out when I can but it looks like one of your template stage setups was wrong.

If you're a patron check out the Monkey King vid or one of the vids on the workshop if you have that.

**Comment by jjburton** [comment]
Just tested. It's a 🐛 | I'll hit it.

**Comment by jjburton** [comment]
Fixed. Will be in next push.

**Comment by broco1001** [comment]
Thank you for the information
