### ISSUE TITLE
Add ability to save custom paths per user/computer in the Project Manager cfg file

### ISSUE THREAD

**Issue by dbokser** [jjburton/cgmTools#79]
It's an annoyance to have to create new projects when working with a group. It would be good if all of the settings from the cfg such as project name, image, desired units and fps stayed consistent between users but users were able to dictate their own project paths which would be saved within the file as well.

**Comment by jjburton** [comment]
per bokser....
I'm thinking when you create a cfg, it puts the paths into the default path category as it currently does
When I load a cfg in project it loads my default path. If I change it because my path is different and save it, it checks it against the default and if it's not the same then it gets my username and creates a new category for user paths and adds my path under my username
Then when I load it up again if my username isn't in the cfg it uses default path

**Comment by jjburton** [comment]
### Working through it...

- Added three dicts
- User dat stores local paths under user name key
- The path load checks for user data and if none found, uses the stored dat


- Added lock system to lock project settings down at will
- Added menu for pushing varous settings and some manually for tangents for example

![image](https://user-images.githubusercontent.com/48218358/77028761-c6700700-6967-11ea-8aee-9933ffc3179b.png)
